### ISSUE TITLE
Reprocess datasets to test ML scoring model and LION

### ISSUE THREAD

**Issue by lmacielvieira** [metaspace2020/metaspace#1177]
Reprocess datasets provided by Bishoy to test ML scoring model

**Comment by sergii-mamedov** [comment]
Total was 300 datasets, finished 295 datasets. Failed datasets:

* 2017-09-04_18h55m50s - xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 80, column 142
* 2017-09-04_17h12m54s - xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 80, column 150
* 2017-09-26_17h17m52s - xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 17, column 148
* 2018-02-16_00h31m57s - no imzML/ibd files on S3
* 2022-05-16_15h02m13s - was delete from production early
