### ISSUE TITLE
Custom adducts bug: H2O loss should be combined with other adducts

### ISSUE THREAD

**Issue by intsco** [metaspace2020/metaspace#119]

**Comment by theodev** [comment]
Not sure why is it a bug. Let's merge with the custom adducts + neutral losses, and discuss before implementing.

**Comment by intsco** [comment]
Custom adducts already implemented but putting H2O into the list of adducts doesn't have the expected effect. That's why it's a bug.

**Comment by theodev** [comment]
Ah this is certainly a wrong way of doing it, as it's a neutral loss

Let's discuss offline

**Comment by intsco** [comment]
Not a bug, just a correct list of adducts should be provided to the engine
