### ISSUE TITLE
Allow to query ion image shape from Python client

### ISSUE THREAD

**Issue by aeisenbarth** [metaspace2020/metaspace#1194]
Currently `SMDataset` has no property from which one can read its shape, which would be useful to correctly size a new array.

My current work-around is to query the databases, query all annotations for the first database, download for the first annotation the first ion image and then just read the shape and trash the array data.

```python
dataset = sm.dataset(id=dataset_id)
formula, adduct = dataset.annotations()[0]
database = dataset.database_details[0]
formula, adduct = dataset.annotations(database=database.id)[0]
shape = dataset.isotope_images(formula, adduct, only_first_isotope=True)[0].shape
```

Since for one dataset, all ion images should have the same shape, the shape could be exposed as a property. This way one could also avoid downloading more data than needed.

**Comment by sergii-mamedov** [comment]
I agree, too many steps to get the ion image size. This information is now in private attributes:
```
acquisition_grid = json.loads(ds._info['acquisitionGeometry'])['acquisition_grid']
print(acquisition_grid)
{'regular_grid': True, 'count_y': 258, 'count_x': 673}
```
I will add this information to the public attributes.

**Comment by sergii-mamedov** [comment]
@aeisenbarth 
metaspace2020 ver. 2.0.2 on PyPI
