### ISSUE TITLE
Improve help & clean up website pages

### ISSUE THREAD

**Issue by LachlanStuart** [metaspace2020/metaspace#144]
* Ensure Google Analytics is tracking enough that we can find out which parts of the site are being used or neglected
* Expand the Help page into more of a knowledge base, adding information from the Speaker Deck slides, details about publishing & linking to datasets, etc.
* Add a page footer so that we have somewhere to put links to Twitter, Gitter, etc.
* Move imzML guide to https://metaspace2020.eu/imzML and update links that are pointing to it

**Comment by theodev** [comment]
Please incorporate how to refer to the results in publications, I've formulated a template here: https://speakerdeck.com/metaspace2020/metaspace-training-guide?slide=44

The hyperlinks for the references: 
- Sumner et al 2007 https://link.springer.com/article/10.1007%2Fs11306-007-0082-2
- Palmer et al 2017 https://www.nature.com/articles/nmeth.4072
