### ISSUE TITLE
LithopsStalledException after MemoryError Exception and restarting lihtops executors

### ISSUE THREAD

**Issue by sergii-mamedov** [metaspace2020/metaspace#1470]
If at least one lithops executor has an Out Of Memory exception, we restart the entire step again with twice as much RAM. When migrating to AWS, we noticed a problem with monitoring restarted lithops executors. The technical description of the problem is also considered in [this issue](https://github.com/lithops-cloud/lithops/issues/1245).

**Comment by abourramouss** [comment]
Hello, I think the out of memory exception is quite ambiguous in Lithops, it refers to ephemeral memory not RAM. Memory-bound workers produce timeouts. Try to increase ephemeral memory instead.

**Comment by sergii-mamedov** [comment]
This bug was fixed in Lithops 3.1.1.
All changes from our side are described in this task: #1482
