### ISSUE TITLE
[Enrichment] Update metabolite enrichment

### ISSUE THREAD

**Issue by lmacielvieira** [metaspace2020/metaspace#1507]

**Comment by Bisho2122** [comment]
Add the following filters for the users **After processing** :

- [ ] If annotation database is HMDB / CoreMetabolome : 
  - [ ] Consider pathway associated annotations
  - [ ] Remove expected & predicted annotations
- [ ] p-value / q-value cutoff 
- [ ] minimum intersection size (default =3) : Intersection size between input metabolites and each term. 

Add the following filters for the users **Before processing** (align with the upload page) :

- [ ] Consider isomers/isobars or not (Bootstrap or not)
- [ ] Background type (Super class, main class, subclass)
- [ ] Molecule type : Lipid, Metabolites
- [ ] Add upload of custom universe (optional)
