### ISSUE TITLE
Individual custom molecules

### ISSUE THREAD

**Issue by theodev** [metaspace2020/metaspace#151]
@LachlanStuart this can be a perfect first task for serverless:

- take mol formula from a user
- pull data from imzML from S3 using serverless
- calculate rho_* and MSM for the images using serverless
- pass it to the webapp for visualization
- no FDR should be calculated, but may be "interpolated" based on FDR and MSM values of annotations from the same dataset 
- (optionally) add the results into "Individual molecules" database

**Comment by intsco** [comment]
The case described in the issue is somewhat implemented through the custom databases. Do we still need to keep the issue given  it's a pretty old one?
