### ISSUE TITLE
Minor release: v1.1

### ISSUE THREAD

**Issue by intsco** [metaspace2020/metaspace#154]
46b677b(ELK logs collection (#152))
5990756(FilterPanel clean-up and "Simple Filter" filter component (#149))
54502c6(Merge branch 'release/v1.0')
a4b6a07(Add toggle to projects page to switch between All Projects and My Projects (#126))
d843a56(Added project manager(s) (#143))
ff49848(Tidy UX on My Account page (#138))
a88e8b9(Bring back apollo client-side cache (#127))
75567c4(Add links to Gitter (#141))
dbed070(I had to change these lines to support earlier versions of python(3.5) (#140))
fc57dfb(Add indicators for group/project invitations/requests (#117))
481d912(Allow admins to change the submitter of datasets (#124))
eed7586(HTTP -> HTTPS where appropriate (#137))
ae990be(Fix log format string (#136))
7b7e15c(Handle conflicts during ElasticSearch indexing (#125))
2690644(Exclude failed datasets from group/project counts. Fix user_group.numDatasets not filtering by group. (#118))
d959adb(Optimize dataset updates (#115))
81edd07(Admin actions for recovering datasets (#114))
5758fcc(Hide unapproved groups from dataset list (#113))
eada783(Fixing "Send request" button functionality on find a group (#107))
1d0c916(Merge remote-tracking branch 'origin/release/v1.0')
07c68d0(More fixes (#111))
cdcf6de(Fixes (#110))
f6aabd2(Tabbed project/group pages & public member lists (#106))
175a926(Merge remote-tracking branch 'origin/release/v1.0')
a65f325(Allow admins to see users' email addresses in metadata (#103))
c54145f(Make the release notes dialog cookie last longer (#104))

**Comment by intsco** [comment]
@LachlanStuart do we want everything that's in master to be added to the release?

**Comment by LachlanStuart** [comment]
@intsco Yes

**Comment by intsco** [comment]
@LachlanStuart please check that all the new features you worked on.

**Comment by LachlanStuart** [comment]
@intsco Looks good to me
