### ISSUE TITLE
Data analysis: Colocalized annotations

### ISSUE THREAD

**Issue by LachlanStuart** [metaspace2020/metaspace#163]
* @LachlanStuart to start by consulting with Ver, D and Sha about what information & interaction is useful, then proceed with UI design. 
* @intsco has already done some work with correlating ion images
* TF-IDF and SSIM may be better algorithms for finding colocalization
* Clustering colocalized ion images should also be considered

**Comment by LachlanStuart** [comment]
Feedback from T:

- [ ] Add colocalization coefficient to CSV
- [ ] Add comment to CSV if the annotations were truncated due to colocalization coefficient thresholding

*Colocalized annotations accordion section:*

- [ ] Use decimal number for colocalization coefficient
- [ ] Condense annotation subtitles to:  “0.8, 5%, 7.5e+4 | 0.6” with hover text: “MSM score, FDR value, max intensity | co-localization score”
- [ ] Use filter icon instead of list icon
- [ ] Rename "distinct localizations" to "representative spatial patterns" or "representative images" and move the link into the annotation view header (next to the share button)
- [ ] Move the "Colocalization Metric" into a cog icon popup on the colocalization tab, similar to the selector for choosing colormap

*Back-end:*

- [ ] Recalculate space requirements now that the `ion` table exists, and lower the threshold for cosine distance to 0.3

*Stretch goals:*

- [ ] Use the most representative ion image when optical images are missing
- [ ] Add a accordion section for the representative images & make them clickable so that it's easy to move between clusters

**Comment by LachlanStuart** [comment]
Feedback from V: Use a configurable, limited list of algorithms so that we don't overwhelm people (similar to the adducts/dbs limited by GraphQL)

**Comment by theodev** [comment]
Yes, very good point from Vitaly

I'd suggest for now to use only 1 simple co-localization: cosine/Pearson

Once we finish the research / evaluation with Katya, consider replacing it
with the best algorithm / score

**Comment by LachlanStuart** [comment]
More feedback:

- [ ] Include the molecule being colocalized against in first place in lists of colocalizations (including CSV)
    - [x] GraphQL changes
    - [ ] UI changes
- [ ] When hovering over a molecular formula in a Related Annotations list, or in the MainImageHeader, show the list of putative molecule names
- [ ] Fix issue with coloc'd images having different heights (`/annotations?ds=2019-02-01_14h32m52s&sections=35&sort=-colocalization` @ 50% zoom)
- [ ] Feature flag
- [ ] Sort sections: Molecules, Coloc, Other adducts, Diag, Metadata
- [ ] Make coloc'd images clickable
