### ISSUE TITLE
Group/Project Descriptions

### ISSUE THREAD

**Issue by LachlanStuart** [metaspace2020/metaspace#168]
It would be cool if these were in Markdown, but that introduces several issues:

* Some markdown libraries are huge. It may be better to render it to HTML on the server
* Security is a big issue with user-submitted content:
    * All forms of scripting must be disabled
    * External images shouldn't be allowed

**Comment by LachlanStuart** [comment]
@Ren22 To clarify the security constraints, here's a list of things to check. You will probably need to change the library's options to conform to these rules. It may even be necessary to run the output through another library like [sanitize-html](https://github.com/punkave/sanitize-html):

Either:
* It must completely disable HTML parsing, e.g. `<b>Foo</b>` gets rendered as text with no bold effect

Or: 
* It must fix/remove HTML tags that are missing their opening or closing tag, e.g. `</div>` or `<pre>` should not break the layout of the page
* It must only allow safe HTML elements from a whitelist of tags that only affect text style. All of these tags are vulnerable to allowing arbitrary scripts to be run, which could be used to steal passwords & data: `<script>`, `<style>`, `<link>`, `<iframe>`, `<svg>`, `<object>`. I'm probably missing some, and there's no guarantee that there aren't going to be any new vulnerable elements in the future, so it's important that it operates on a "only allow known-to-be-safe elements" instead of a "disallow known-to-be-unsafe elements" basis.
* It must be able to block images from external sources, as they can be used to track users without their consent. Ideally we'd be able to whitelist our own domains, but that's not a strict requirement.

Also:
* For links it should add `rel="nofollow noopener noreferrer"` to the `<a>` element, as this prevents the target site from being able to have any access to the page that opened the link, and indicates to search engines that we don't trust that link.

Please let me know if you want me to review any libraries/find libraries that fit these criteria, and let me know when you've decided on which libraries to use so I can check they're safe before you put time into integrating them.

**Comment by Ren22** [comment]
@LachlanStuart thanks for a very detailed clarification, I'm just wondering - would it be ok if I write my own checker maybe based on these libraries? That sounds as interesting task for me.
Also: what are the potential ways to have these descriptions added on Metaspace? Are we going to provide somewhere a form to input it as part of the form?

**Comment by LachlanStuart** [comment]
@Ren22 I mentioned it at lunch, one of the principles of good security is to avoid writing your own security code, relying instead on community-reviewed packages. If you can't find anything satisfactory, I suggest you use that sanitize-html library - its default values are almost perfect, it only needs two changes:
* Don't allow `<iframe>` at all
* Add `rel="nofollow noopener noreferrer"` to all `<a>` elements (this can be done with the `transformTags` option)

The description should be editable on the "Settings" tab of the group/project page. It should be similar to the GitHub editor - have a Write and Preview tab, as well as a hint that Markdown is supported with a link to a reference guide.
