### ISSUE TITLE
Move webapp into Vue CLI & enable code linting

### ISSUE THREAD

**Issue by LachlanStuart** [metaspace2020/metaspace#211]
Vue CLI bundles & integrates many common build tools used with Vue, so that they can be easily used without having to be individually configured. This also makes it easier to keep up-to-date with the latest tools.

We're currently running a lot of our build tools on older versions because upgrading them is a huge hassle due to changes in how they work and dependencies between different versions of libraries. Lately we've started getting warnings about our browser support list because the data it uses hasn't been updated in over 6 months. It now looks like it would be easier to strip all these tools out and move webapp to Vue CLI than to try to manually upgrade these tools.

The main difficulty in switching to Vue CLI is dealing with the web server part of webapp. Vue CLI was designed to build statically-served JS files and doesn't directly support hosting  additional server functionality. Webapp hosts a service to help with uploading files which doesn't fit neatly into the Vue CLI model. The simplest fix is to move upload functionality into the graphql project.

**Comment by Ren22** [comment]
nice, this is a worth doing step , I've already read about people started using vue cli giving some positive feedback

**Comment by LachlanStuart** [comment]
There are some performance advantages for our end-users too:
* Serving the HTML/JS files directly from nginx will always be fast, even when the server is under load
* The JS files will have hashes in their filenames, which means we can change them to be cacheable forever (`Cache-Control: Immutable`), reducing the number of requests the browser needs to make
* Vue CLI has [Modern Mode](https://cli.vuejs.org/guide/browser-compatibility.html#modern-mode), which makes 2 copies of the JS - a smaller & faster copy for modern browsers and a larger & more compatible copy for older browsers
