### ISSUE TITLE
Iso images not aligned with isotope spectrum

### ISSUE THREAD

**Issue by intsco** [metaspace2020/metaspace#222]
![image](https://user-images.githubusercontent.com/1176502/52433165-b6eb8100-2b0c-11e9-89fe-dadb82428eb9.png)

The second shown image is actually the forth one

**Comment by intsco** [comment]
@LachlanStuart what kind of review is needed?

**Comment by LachlanStuart** [comment]
@intsco I had forgotten to close this. It was fixed in #226
