### ISSUE TITLE
Add linting to enforce code style in sm-graphql

### ISSUE THREAD

**Issue by LachlanStuart** [metaspace2020/metaspace#227]
Consistent code style makes it easier for both newcomers and regular coders to understand the codebase. It also helps to identify some classes of bugs, and reduces the distraction of "ugly code" while working on existing code.

There are tools available that will not only enforce consistent code style, but also automatically fix existing code. In addition there are several pre-made code style guides that we could copy & tweak.

For TypeScript/JavaScript, ESLint is the most common, and is built in to Vue CLI (#211). Recent plugins to it allow it to support TypeScript.

For Python there are many options including Pylint and Black, although some of them enforce an opinionated code style, so research is needed before choosing one.

Ideally any linter we implement should be configured based on our existing code style, though one exception has been identified:
* In JS, there is a general consensus that removing semicolons would make it easier to switch between JS and Python

**Comment by Ren22** [comment]
sounds good, shall we also refactor/rewrite the rest of components in web-app into TS as part of this issue? If that's the case I'd be happy to have my hands on it.

**Comment by LachlanStuart** [comment]
@Ren22 Preferably not as part of this issue. ESLint should be able to apply the same rules to both TS and JS, so there shouldn't be a need for it. The type of code issues that ESLint finds are usually very self-contained, so I wouldn't expect any major refactoring to be needed.

On the JS side, I envision ~50% of this task being configuring ESLint to get it targeting our existing code style, and the other ~50% manually fixing code that ESLint doesn't have an automatic fix for.

On the Python side, I envision significantly more time evaluating linters & how well they work with PyCharm and our codebase. Unlike WebStorm, PyCharm doesn't have built-in support for any linters, so it's still unknown whether a linter would fit well into our workflow.

TBH, I'm still on the fence about the value of TypeScript in webapp. Every interaction with Vue forces data to go through an untyped interface, causing TypeScript to miss a huge proportion of issues. I don't think it's worth the time to do a full rewrite - I'd prefer to keep going on a convert-as-needed basis.
