### ISSUE TITLE
Scheduled/regular backups of imzML, ibd, db & raw input data

### ISSUE THREAD

**Issue by LachlanStuart** [metaspace2020/metaspace#335]
Amazon S3 Glacier is a good candidate https://aws.amazon.com/glacier/faqs/?nc=sn&loc=6

**Comment by intsco** [comment]
Should be closed once versioning and MFA-Delete are enabled for our S3 buckets.

**Comment by intsco** [comment]
Closing in favor of https://github.com/metaspace2020/private-info/issues/2
