### ISSUE TITLE
Consider buying AWS reserved instances for web hosts

### ISSUE THREAD

**Issue by intsco** [metaspace2020/metaspace#498]
costs optim strategy
3 on-demand instances 
2x cost compared for long-term reserved instances

**Comment by intsco** [comment]
https://eu-west-1.console.aws.amazon.com/ec2/v2/home?region=eu-west-1#SavingsPlans:

**Comment by sergii-mamedov** [comment]
I think the best for us will be:
   * Term lenght - 1 year
   * Payment options - No Upfront
   * Standard (Non convertible)

```
            | effective |           |
  instance  | price $/h | savings % |
------------+-----------+-----------+
 r5a.large  |   $0.080  |    37%    |
 r5a.xlarge |   $0.160  |    37%    |
 t3a.medium |   $0.036  |    37%    | 
```

Pricing page: https://aws.amazon.com/ec2/pricing/reserved-instances/pricing/

**Comment by sergii-mamedov** [comment]
The following types have been ordered:
1. r5a.large - 1 (expires 14.04.2022)
2. r5a.xlarge - 2 (expires 14.04.2022)
3. t3.medium - 1 (expires 08.04.2022)
