### ISSUE TITLE
Consider ion image normalization

### ISSUE THREAD

**Issue by LachlanStuart** [metaspace2020/metaspace#501]
On centroided data it's not technically possible to do TIC or RMS normalization numerically correctly, as centroiding doesn't necessarily preserve the total intensity. Regardless, applying normalization based on the per-pixel sum of raw intensities seems to improve some ion images, reducing noise and improving visibility of features.

| Annotation | Before | After | "TIC" / sum-intensity image |
|---|---|---|---|
| [Link](https://metaspace2020.eu/annotations?ds=2018-08-31_10h21m33s&mol=C47H83O13P&add=-H&fdr=0.05&sections=11&hideopt=1) | ![image](https://user-images.githubusercontent.com/26366936/70535626-aa391e80-1b5d-11ea-8c2a-d20f2da9dd73.png) | ![image](https://user-images.githubusercontent.com/26366936/70535644-b1602c80-1b5d-11ea-8966-29591b6efdff.png) | ![image](https://user-images.githubusercontent.com/26366936/70535656-b7560d80-1b5d-11ea-825b-153024509adc.png) |
| [Link](https://metaspace2020.eu/annotations?ds=2017-06-30_07h26m26s&mol=C44H86NO8P&add=%2BH&fdr=0.05&sections=11&hideopt=1) | ![image](https://user-images.githubusercontent.com/26366936/70536445-ffc1fb00-1b5e-11ea-86e4-a0c91de05c13.png) | ![image](https://user-images.githubusercontent.com/26366936/70536454-06507280-1b5f-11ea-82a5-d1d65af0342d.png) | ![image](https://user-images.githubusercontent.com/26366936/70536472-0e101700-1b5f-11ea-9503-777bf1efeef7.png) |

There's no need to change any code that would affect the MSM scores - only the Chaos metric has the potential to change, but the effect would be so small it's not worth doing. If we instead computed and saved a sum-intensity and possibly an RMS image for each dataset, Normalization could be applied on-the-fly in the browser code. Once the code is in place, it could also be used for normalizing by a user-selected standard molecule's ion image.

The big downside is that in cases such as example 2 above, it's unclear which of the brighter features of the "after" image truly represent an increase in concentration, and which are just amplified due to the "shadows" in the "TIC" image, which could have been caused by unrelated phenomena.

**Comment by theodev** [comment]
@LachlanStuart @richardgoater bringing it up again -- fits nicely into the planned image viewer
