### ISSUE TITLE
Investigate replacing FineUploader

### ISSUE THREAD

**Issue by LachlanStuart** [metaspace2020/metaspace#529]
It's deprecated and seems to be a bit flakey. Is there a good replacement for large upload directly to AWS S3?

**Comment by richardgoater** [comment]
I've previously used this: http://resumablejs.com/. Found it to be reliable and customisable, but doesn't come with UI.

**Comment by LachlanStuart** [comment]
Closing this to clean up our todo list.

We investigated replacement candidates and agreed to go with Uppy, but haven't scheduled when we will convert the Datasets page.
