### ISSUE TITLE
Add migration for data updates to existing databases

### ISSUE THREAD

**Issue by intsco** [metaspace2020/metaspace#576]
Convert hidden databases into custom databases that belong to the EMBL group.

Copy additional metadata (fullName, link, citation, description) for public databases from [DatabaseDescriptions.vue](https://github.com/metaspace2020/metaspace/blob/feat/custom-moldbs/metaspace/webapp/src/modules/MetadataEditor/inputs/DatabaseDescriptions.vue) into the database.

**Comment by LachlanStuart** [comment]
I've shoehorned an additional, related task into this one so that it's not forgotten: adding the existing hard-coded metadata (description, etc.) for molDBs into the database.
