### ISSUE TITLE
Custom Databases UI

### ISSUE THREAD

**Issue by LachlanStuart** [metaspace2020/metaspace#580]
Feature specification: https://docs.google.com/document/d/1ugB7AAKZ3Scgex2yqwulva8s7s5n2T2VPr0h6_-yL8g/edit

- [ ] UI to support CRUD of custom databases. Per previous discussion, this would fit most easily in the Group page, as custom DBs are scoped within groups.
- [ ] Updates to the MetadataEditor to support custom DBs
    * Database selection should differentiate between global/officially supported databases and group-specific databases. In future we may also have a global-but-community-supplied/unsupported databases section.
    * Full name, Description, etc. of databases should be retrieved from API instead of hard-coded
    * Should still be usable with 50+ databases (note: admins will be able to see all groups' databases...)
    * (new feature) Should make it impossible to deselect the default databases, because they're re-added by the UI anyway
- [ ] Update database filter component to support extra databases
    * Should differentiate between global vs group-specific databases
    * Should only show current user's groups' databases in the unfiltered list, but should be searchable for other groups' public databases

**Comment by intsco** [comment]
@richardgoater This issue is completely resolved, right?

**Comment by richardgoater** [comment]
@intsco mostly yes. I still think selecting databases before upload should be improved, but this can go to a new issue. Doing this would solve this item (which caused Veronika issues):
> (new feature) Should make it impossible to deselect the default databases, because they're re-added by the UI anyway
