### ISSUE TITLE
Multiple image viewer

### ISSUE THREAD

**Issue by LachlanStuart** [metaspace2020/metaspace#584]
Supersedes #128 

In MSiReader, Måns demonstrated an image overlay tool where you can select a number of different ion images to show simultaneously, assign each one a color, scale them, etc.

Andreas raised that he also has a use-case for supporting multiple optical images (full description in comments).

This effectively requires an interface where you can select multiple annotations and optical images, and for each one have individual controls to:
* Quickly toggle its visibility
* (Annotations only) Toggle visibility of a scalebar
* (Up for discussion) Split an RGB optical image into separate R, G and B layers (or allow this to be selected during image upload)
* Apply a specific coloration or colorscale
* Scale its intensity
* Change its opacity
* Change its rendering order

Some work will also be needed to determine the best blending mode for the layers, as the premise for #128 is that the current blending mode often produces ugly results.

This also relates to the "High-resolution ion thumbnails" diagnostic. Ideally ion thumbnails would link to the multiple image viewer

**Comment by LachlanStuart** [comment]
This is the explanation of @aeisenbarth 's use case:

> There were two projects where this need came up:
> A. In the SpaceM revision we had MALDI datasets uploaded by Måns that had a post-MALDI microscopy overlayed and I wanted to overlay another stained microscopy. I had to clone the dataset (including unnecessary reprocessing) for not replacing/removing the existing overlay. In that case, overlays could have **different matrices* each. We would need to discuss whether this is important and a recurring need.
> B. For SpaceM, the color channels of different stains are visually overloading especially when the MALDI image is overlay on top of them. By uploading the individual channels as **multiple** (e.g. grayscale) image **files** (but with **same matrix**) one could switch to the channel of interest and see only this channel and the MALDI overlay. There could be more than 3 stains, so separate files is simpler than having Metaspace filter a channel out of an RGB file. One could also want to display several channels at a time or assign a specific color to a channel, but that could be done offline in an image editor and then uploading it as a new image. [Example with many channels](https://metaspace2020.eu/annotations?prj=029b4e3c-053c-11ea-9d77-0b8d14e792b0&ds=2020-02-07_13h13m58s), [example with only green channel](https://metaspace2020.eu/annotations?ds=2020-04-02_17h47m53s)

**Comment by richardgoater** [comment]
Related issue: https://github.com/metaspace2020/metaspace/issues/633

**Comment by LachlanStuart** [comment]
Implemented in #679
