### ISSUE TITLE
Convert JSON databases to MolecularDB

### ISSUE THREAD

**Issue by aeisenbarth** [metaspace2020/metaspace#729]
There is an inconsistency when switching between [`SMInstance.databases`](https://github.com/metaspace2020/metaspace/blob/master/metaspace/python-client/metaspace/sm_annotation_utils.py#L1463) and [`SMDataset.database_details`](https://github.com/metaspace2020/metaspace/blob/master/metaspace/python-client/metaspace/sm_annotation_utils.py#L968). 

The first returns a `MolecularDB`, the latter (like most SMDataset accessor methods) returns a list of raw JSON objects. As a consequence, when accessing database attributes one has to use square parentheses instead of the dot operator.

**Comment by LachlanStuart** [comment]
This will be resolved in version 1.8.9 to be released once #892 is merged.

My solution should be backwards-compatible with existing code - it adds a `__getitem__` function to `MolecularDB` so that `dataset.database_details[0].name` and `dataset.database_details[0]['name']` get the same value.
