### ISSUE TITLE
Add KEGG database

### ISSUE THREAD

**Issue by LachlanStuart** [metaspace2020/metaspace#856]
We have access to the KEGG database, and it's well known among biologists. While the main value of the database is the reactions and pathways (which likely will be awesome for enrichment analysis), as a starting point we should import the lists of molecules.

The main files on the network drive (should be accessible to anyone in the team):
* `/g/scb/bork/yuan/kegg/ligand/compound.tar.gz`
* `/g/scb/bork/yuan/kegg/ligand/glycan.tar.gz` (should be imported as a separate DB)

The files are in a custom format, so you'll likely need to write a converter script. This should be saved in `metaspace/engine/scripts`.

These files are updated regularly, so be sure to use the modification date of the files as the database version on METASPACE.

**Comment by sergii-mamedov** [comment]
### Filtration of molecules

We decided to add only the **compound** database. Most of the information about molecules is in the `compaund` file, the INCHI information is in the `compaund.inchi` file. For the final list, we had to filter out some of the molecules. The criteria for filtering molecules were as follows:

1. The formula ends in `R` or `R with some number`:
  * C2H4NO2R
  * C4H6N2O3R2
  * C10H14N4O4S2R4

2. Formula ends in `n` or `n-1`:
  * C4H6N2O3R2(C7H9N2O2R)n
  * C5H8O(C5H8)n-1

3. Formula ends in `(R2)`:
  * C19H30N12O6(R1)(R2)

4. For a molecule there is no `INCHI`.

The remaining molecules were saved to a TSV file.


### Generation of images of molecules

Image generation (SVG) was carried out for each molecule from the TSV file. Generation with Open Babel gave a lot of errors and warnings:

1. 19 error cases "Open Babel Error  in SVGFormat. Molecule  needs 2D coordinates to display in SVGformat"
   The files were deleted as they did not contain images of molecules. Also, the molecules were removed from the TSV file.
   List of molecules: `[C01358, C08142, C08219, C12538, C12567, C12568, C12569, C12570, C13140, C13198, C13515, C13563, C14042, C15226, C15473, C17379, C17392, C18670, C18672]`

2. 4 warning cases "Open Babel Warning  in InChI code. Unsupported stereo type has been ignored."
   Files were not deleted. List of molecules: `[C08596, C08606, C13431, C14044]`

3. 14 warning cases "Open Babel Warning  in InChI code. For InChI=INCHI; Problems/mismatches: Mobile-H( ....."
   Files were not deleted. List of molecules: `[C04446, C04536, C05306, C05307, C06488, C11242, C11243, C11829, C11850, C11851, C18151, C19423, C21217, C21435]`

4. 719 warning cases "Open Babel Error  in TetStereoToWedgeHash. Failed to set stereochemistry as unable to find an available bond"
   Files were not deleted. List of molecules: `[C00695, C00735, C00765, C00859, C01091, C01124, C01301, C01433, C01443, C01512, C01626, C01699, C01780, C01794, C01921, C02035, C02140, C02256, C02528, C02673, C02821, C02942, C03579, C03594, C03747, C03963, C04070, C04318, C04578, C04661, C04715, C04859, C05284, C05291, C05296, C05337, C05444, C05445, C05446, C05447, C05448, C05449, C05450, C05451, C05452, C05453, C05454, C05455, C05458, C05460, C05465, C05466, C05467, C05471, C05472, C05473, C05474, C05475, C05476, C05482, C05489, C05497, C05498, C05683, C06071, C06091, C06094, C06095, C06096, C06341, C06522, C06543, C06624, C06694, C06973, C07005, C07201, C07204, C07310, C07369, C07413, C07552, C07654, C07880, C08029, C08176, C08178, C08179, C08180, C08182, C08433, C08618, C08619, C08628, C08630, C08631, C08632, C08635, C08636, C08654, C08655, C08657, C08658, C08659, C08661, C08662, C08663, C08664, C08665, C08666, C08667, C08668, C08669, C08671, C08673, C08674, C08675, C08676, C08677, C08678, C08679, C08680, C08681, C08682, C08683, C08684, C08686, C08687, C08688, C08689, C08690, C08691, C08692, C08693, C08694, C08696, C08697, C08698, C08699, C08700, C08701, C08702, C08704, C08706, C08707, C08708, C08710, C08711, C08713, C08715, C08738, C08746, C08747, C08748, C08749, C08750, C08751, C08752, C08753, C08754, C08755, C08756, C08757, C08759, C08760, C08763, C08764, C08769, C08770, C08772, C08776, C08777, C08780, C08781, C08782, C08783, C08784, C08787, C08788, C08806, C08831, C08851, C08852, C08853, C08857, C08863, C08864, C08865, C08870, C08871, C08874, C08877, C08878, C08885, C08886, C08887, C08888, C08889, C08890, C08891, C08892, C08893, C08894, C08895, C08896, C08897, C08898, C08899, C08900, C08901, C08902, C08904, C08906, C08907, C08908, C08909, C08910, C08911, C08912, C08913, C08914, C08915, C08916, C08917, C08918, C08919, C08935, C08936, C08937, C08944, C08945, C08946, C08961, C08971, C08991, C09020, C09034, C09040, C09042, C09045, C09050, C09062, C09065, C09068, C09073, C09077, C09080, C09081, C09084, C09085, C09088, C09095, C09096, C09100, C09101, C09102, C09104, C09105, C09108, C09109, C09111, C09114, C09117, C09122, C09125, C09127, C09128, C09129, C09132, C09134, C09135, C09138, C09139, C09151, C09153, C09156, C09161, C09172, C09173, C09174, C09177, C09184, C09185, C09192, C09193, C09195, C09198, C09207, C09214, C09215, C09218, C09219, C09242, C09244, C09252, C09254, C09255, C09274, C09286, C09288, C09291, C09295, C09296, C09299, C09302, C09344, C09346, C09354, C09358, C09359, C09397, C09407, C09416, C09417, C09425, C09434, C09435, C09443, C09447, C09451, C09456, C09468, C09469, C09472, C09486, C09487, C09491, C09498, C09499, C09508, C09509, C09510, C09525, C09531, C09532, C09539, C09551, C09557, C09587, C09600, C09639, C09647, C09648, C09697, C09698, C09766, C09768, C09773, C09775, C09776, C09779, C09783, C09784, C09787, C09788, C09790, C09796, C09797, C09799, C09802, C09804, C09855, C09886, C09888, C09934, C09992, C10124, C10132, C10173, C10279, C10353, C10363, C10380, C10383, C10598, C10768, C10774, C10778, C10780, C10782, C10796, C10803, C10807, C10815, C10816, C10817, C10819, C10820, C10821, C10822, C10824, C10826, C10827, C10831, C11047, C11231, C11321, C11626, C11636, C11640, C11641, C11642, C11643, C11644, C11645, C11646, C11647, C11648, C11649, C11650, C11651, C11652, C11653, C11656, C11657, C11658, C11659, C11660, C11661, C11662, C11663, C11666, C11667, C11668, C11669, C11670, C11671, C11674, C11675, C11676, C11677, C11700, C11783, C11784, C11812, C11853, C11856, C11857, C11858, C11859, C11860, C11861, C11862, C11863, C11864, C11865, C11866, C11867, C11868, C11871, C11876, C11899, C11900, C11905, C12170, C12171, C12243, C12308, C12512, C12656, C12666, C12888, C13055, C13358, C13422, C13554, C13718, C13849, C13974, C14159, C14160, C14161, C14162, C14255, C14475, C14553, C14555, C14587, C14588, C14606, C14618, C14643, C14649, C14669, C14675, C14683, C14758, C14887, C14891, C14907, C14922, C14932, C14939, C14946, C14964, C14973, C14990, C15002, C15011, C15022, C15034, C15041, C15047, C15098, C15103, C15115, C15132, C15164, C15165, C15172, C15187, C15256, C15274, C15275, C15285, C15287, C15288, C15291, C15299, C15302, C15303, C15306, C15307, C15314, C15320, C15329, C15349, C15351, C15355, C15356, C15363, C15364, C15372, C15374, C15399, C15401, C15402, C15403, C15434, C15456, C15516, C15518, C15520, C15559, C15568, C15613, C15614, C15636, C16258, C16259, C16260, C16261, C16816, C16819, C16841, C16859, C16868, C16875, C16890, C16912, C16962, C16990, C16998, C17000, C17003, C17004, C17012, C17013, C17029, C17030, C17031, C17032, C17033, C17034, C17035, C17036, C17038, C17041, C17042, C17049, C17051, C17052, C17053, C17066, C17068, C17069, C17074, C17075, C17193, C17331, C17332, C17335, C17336, C17337, C17339, C17343, C17345, C17346, C17428, C17429, C17430, C17431, C17442, C17459, C17460, C17461, C17468, C17470, C17485, C17508, C17522, C17523, C17538, C17539, C17553, C17613, C17644, C17647, C17649, C17650, C17651, C17652, C17653, C17654, C17655, C17656, C17660, C17661, C17662, C17664, C17667, C17668, C17689, C17726, C17727, C17737, C17766, C17767, C17768, C17769, C17831, C17832, C17833, C17841, C17842, C18015, C18016, C18038, C18039, C18045, C18075, C18124, C18145, C18164, C18296, C18961, C19512, C19656, C19662, C19663, C19726, C19863, C19898, C19902, C19942, C19953, C19954, C19990, C19992, C20026, C20035, C20061, C20132, C20150, C20172, C20181, C20274, C20632, C20633, C20678, C20707, C20709, C20713, C20715, C20716, C20725, C20736, C20777, C20778, C20779, C20780, C20789, C20790, C20866, C20868, C21438, C21469, C21471, C21553, C21577, C21678, C21682, C21683, C21690, C21700, C21765, C21909, C21910, C21911, C21912, C21978, C21979, C22014, C22108, C22109, C22127, C22128, C22129, C22200]`
