### ISSUE TITLE
TIC image generation (Back-end)

### ISSUE THREAD

**Issue by LachlanStuart** [metaspace2020/metaspace#885]
METASPACE currently provides no way to get the TIC of individual spectra. The TIC can be very useful for downstream analysis for a number of reasons:
* Normalizing ion images by the TIC often reduces noise and makes spatial effects clearer
* ML techniques can often use spectrum TICs as a proxy for spectrum quality, density, or limit of detection
* The TIC image can be helpful to diagnose acquisition problems (e.g. someone bumped the instrument and parts of the image were acquired with reduced sensitivity)

TIC normalization is simply dividing each intensity value for each peak by the sum of all intensities in the same spectrum. E.g. if a peak has 1e4 intensity and the total spectrum is 1e5, the TIC-normalized intensity for that peak becomes `1e4 / 1e5 = 0.1` or `10%`.

This task has several parts:

#### Record TIC information while loading ImzML files
- [x] If the information is available in the ImzML file metadata, use that value. It appears like this:
```xml
<cvParam cvRef="MS" accession="MS:1000285" name="total ion current" value="112074.63582611084"/>
```
- [x] If it's not available in the ImzML file metadata, simply sum the values in the intensity array from the ibd file

#### Save the result
- [x] Reuse the [database structure from the shelved Diagnostics branch](https://github.com/metaspace2020/metaspace/commit/d703477283d51f2f246e6f6ba83e6f0adfccafb6#diff-8bbdb7ed07e56df4effabaabdca379120af1618d3aa09e76f22cbb58f97a9a4a), as this will help with integrating with future diagnostics information. 
* This structure was designed so that additional metadata could be supplied along with each image (not needed in this case, but used for many other proposed diagnostics), and so that the images could be easily cleaned up when a dataset is deleted.
* `jobId` should be `NULL` for TIC images, because they do not vary with database/annotations.

- [x] The output should be a 2D image with 1 value per spectrum. 
* This image must align with ion images, so the same coordinate system math should be used
* The format should be a [`.npy`-serialized](https://numpy.org/doc/stable/reference/generated/numpy.save.html?highlight=save#numpy.save) float32 array, where missing pixels are NaN values
    * The reason for using this format is that `.npy` files encode shape & dtype information, and often don't need any additional metadata to decode. There are also several JS libraries that can load `.npy` files, making it easy to use from the front-end.
* Use the existing image service for saving the image. It may need changes for saving binary files, but it's still the best way to manage dataset-related objects in S3, so it should be reused.

#### Migrate existing datasets

- [x] Make a migration script that creates TIC images for existing datasets
* Most datasets are still only on S3, so it would be best if this can also run on S3

#### Add a GraphQL API

- [x] For now it should be enough to just mirror the database structure into sub-resolvers in the `Dataset` query resolver.

#### Integrate with Python Client

- [x] Add an additional function to `SMDataset` to retrieve & load the TIC image. Make sure to pass `ignore_pickle=True` to `np.load` to avoid any security hazards.
- [x] Add a way to automatically normalize images when they're downloaded through `SMDataset.isotope_images` and `all_annotation_images`. It would make sense to expose this through the existing `scale_intensity` parameter, e.g. `scale_intensity='tic_normalize'`

**Comment by sergii-mamedov** [comment]
> TIC-normalized intensity for that peak becomes 4e6 / 5e6 = 0.1 or 10%.

It seems to be 0.8

**Comment by LachlanStuart** [comment]
> > TIC-normalized intensity for that peak becomes 4e6 / 5e6 = 0.1 or 10%.
> 
> It seems to be 0.8

My mistake. I meant to say this:
E.g. if a peak has *1e4* intensity and the total spectrum is *1e5*, the TIC-normalized intensity for that peak becomes *1e4* / *1e5* = 0.1 or 10%.
